name: PS2 Manager linux nightly build

on:
  push:
    branches: ["main"]

jobs:
  Linux:
    name: Build PS2 Manager Linux Nightly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Building PS2Manager for Linux...
        run: |
          CGO_ENABLED=0
          GOOS=linux
          for arch in 386 arm arm64 mips mips64 ppc64 riscv64; do
            echo "Building for $arch..."
            GOARCH=$arch go build -ldflags '-s -w' -trimpath -o ps2manager-linux-$arch
          done

      - name: Create release message body...
        id: release_body
        shell: bash
        run: |
          body="$(git log --oneline -n 10)"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "RELEASE_BODY=$body" >> $GITHUB_OUTPUT

      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          tag: nightly
          overwrite: true
          file_glob: true
          file: ps2manager-*
          body: |
            ${{ steps.release_body.outputs.RELEASE_BODY }}
