name: PS2 Manager linux nightly build

on:
  push:
    branches: [ "main" ]

jobs:
  Linux:
    name: Build PS2 Manager Linux Nightly
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Building PS2Manager...
        run: go build -o ps2manager-linux-amd64
      - name: Upload RetroArch AppImage
        uses: svenstaro/upload-release-action@v2
        with:
          file: ps2manager-linux-amd64
          tag: nightly
          asset_name: ps2manager-linux-amd64
          overwrite: true
